---
title: "Random Forest for Predicting TBARS Assay Results from Oxidative Stress Genes "
author: "Imogen Stafford"
date: "11/10/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Packages from Library 

```{r}
library(caret)
library(tidyverse)
library(randomForest)
library(gbm)
```


#Load up and Configure Data

```{r}
rosdata <- read.delim("//filestore.soton.ac.uk/users/iss1g18/mydocuments/PhD/ROS Analysis/Data Files/rosdatanew.txt")

MyVars <- c( "tbars_final_z","NOX1", "CYBA", "CYBB", "NCF2","NCF4",  "RAC2",
             "DUOX2", "NOXA1","NOXO1", "DUOXA1", "DUOXA2", "DUOX1", "NOX3", "NOX4", "NOX5")

mldata <- na.omit(rosdata[MyVars])
```

#Label FRAP assay results as "high", "mid", "low". Make a new column in the dataframe for this information.

```{r}
mldata$tbars_bin <- mldata$tbars_final_z
mldata$tbars_bin[mldata$tbars_final_z > quantile(mldata$tbars_final_z, probs = 0.5)] <- print("high")
mldata$tbars_bin[mldata$tbars_final_z <= quantile(mldata$tbars_final_z, probs = 0.5)] <- print("low")
mldata$tbars_bin <- as.factor(mldata$tbars_bin)

#Check categories are in their correct proportion
summary(mldata$tbars_bin)

#Remove frap z-scores
mldata <- mldata[,-1]

#Remove data in "mid" category
data <- subset(mldata, tbars_bin=="high" | tbars_bin=="low")

#remove mid level
data$tbars_bin <- factor(data$tbars_bin)
summary(data$tbars_bin)

```

#FRAP model: remove midpoindata splitting

```{r}
#begin data partition
set.seed(23)
trainIndex <- createDataPartition(data$tbars_bin, p = .65, 
                                  list = FALSE, 
                                  times = 1)
head(trainIndex)

tbarsTrain <- data[ trainIndex,]
tbarsTest  <- data[-trainIndex,]
summary(tbarsTrain$tbars_bin)
summary(tbarsTest$tbars_bin)

```

#Random Forest Model Training

```{r}
set.seed(23)
#method="rf"
fitControl <- trainControl (##10-fold CV
  method = "repeatedcv",
  number=10,
  repeats=10)

#Mtry <- sqrt(ncol(fraTrain))
#tuneGrid <- expand.grid(.mtry=mtry)
set.seed(23)
rfFit <- train(tbars_bin ~ ., data = tbarsTrain, method ="rf", metric="Accuracy",Mtry= sqrt(ncol(tbarsTrain)), trControl = fitControl )
plot(rfFit)

#summary(rfFit)

#method="gbm"
set.seed(23)
gbmGrid <-  expand.grid(interaction.depth = c(1,5, 9), 
                        n.trees = (1:30)*50, 
                        shrinkage = 0.1,
                        n.minobsinnode = 20)

gbmFit2 <- train(tbars_bin ~ ., data = tbarsTrain, 
                 method = "gbm", 
                 trControl = fitControl, 
                 verbose = FALSE, 
                 ## Now specify the exact models 
                 ## to evaluate:
                 tuneGrid = gbmGrid)
plot(gbmFit2)

```





